upstream cloudon_api {
    server api:8000;
}

server {
    listen 80;
    listen [::]:80;
    server_name bi.boxvisio.com adminpanel.boxvisio.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location = / {
        if ($host = bi.boxvisio.com) { return 302 /tenant/dashboard; }
        if ($host = adminpanel.boxvisio.com) { return 302 /admin/dashboard; }
        return 302 /;
    }

    location / {
        proxy_pass http://cloudon_api;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
